preload = ~/.config/hypr/wallpapers/dark-circle.png

splash = false

wallpaper {
	monitor = eDP-1
	path = ~/.config/hypr/wallpapers/dark-circle.png
}

# Fallback for any other (e.g. external) monitor.
wallpaper {
	monitor =
	path = ~/.config/hypr/wallpapers/dark-circle.png
}
