-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- HYPRLAND CONFIG (modular).                            --
-- See https://wiki.hypr.land/Configuring/Start/         --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

require("conf/monitors")
require("conf/autostart")
require("conf/environment")
require("conf/look-and-feel")
require("conf/animations")
require("conf/input")
require("conf/keybindings")
require("conf/window-rules")
